apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: accessibility-reporting-tool-frontend
  namespace: a11y-statement
  labels:
    team: a11y-statement

spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /minside/utkast/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /minside/utkast/api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://a11y-statement.ansatt.nav.no"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
